apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: ${PROMETHEUS_URL}
    basicAuth: false
    isDefault: true
    jsonData:
      httpHeaderName1: Authorization
      httpHeaderValue1: Bearer ${PROMETHEUS_TOKEN}
    secureJsonData:
      httpHeaderValue1: Bearer ${PROMETHEUS_TOKEN}
